<?php
set_time_limit(0);
//date_default_timezone_set("Asia/Calcutta");
session_start();
date_default_timezone_set(''.$_SESSION['timezone'].'');

if(isset($_POST['to_get']) && $_POST['to_get'] == 'get_exception_report'){

    include_once '../../lib/bo/DeviceManager.php';
    include_once '../../lib/bo/VehicleManager.php';
    include_once '../../lib/bo/UnitManager.php';
    include_once '../reports/reports_fuelefficiency_functions.php';
    include_once 'exception_class.php';
    
    $s_date = isset($_POST['SDate']) ? $_POST['SDate'] : date('d-m-Y');
    $e_date = isset($_POST['EDate']) ? $_POST['EDate'] : date('d-m-Y');
    $s_time = isset($_POST['STime']) ? $_POST['STime'].':00' : "00:00:00";
    $e_time = isset($_POST['ETime']) ? $_POST['ETime'].':59' : "23:59:59";
    $cp_start = isset($_POST['checkpoint_start']) ? $_POST['checkpoint_start'] : "";
    $cp_end = isset($_POST['checkpoint_end']) ? $_POST['checkpoint_end'] : "";
    $cp_start_name = isset($_POST['cp_start_name']) ? $_POST['cp_start_name'] : "";
    $cp_end_name = isset($_POST['cp_end_name']) ? $_POST['cp_end_name'] : "";
    $report_type = isset($_POST['report_type']) ? $_POST['report_type'] : "";
    $report_type_input = isset($_POST['report_type_input']) ? $_POST['report_type_input'] : 100;
    $condition = isset($_POST['condition']) ? $_POST['condition'] : 'gt';
    $con = ($condition == 'lt_eq') ? "<=" : '>';
    
    /*display details*/
    $TableTitle = "Exception Report";
    $report_type_text = ucfirst($report_type)." $con $report_type_input";
    $TableSubHeaderLeft = "Start Date: $s_date $s_time<br/>End Date: $e_date $e_time<br/>Start Checkpoint: $cp_start_name<br/>End Checkpoint: $cp_end_name<br/>Report type: $report_type_text";
    $TableSubHeaderRight = "Generated by: ".$_SESSION['username']."<br/>Generated on: ".date('d-m-Y H:i');
    /**/
    
    if(validate_input($s_date,$e_date)){
        $customerno = $_SESSION['customerno'];
        $start_date = date('Y-m-d', strtotime($s_date));
        $end_date = date('Y-m-d', strtotime($e_date));
        $reports = getdailyreport_check($start_date, $end_date, $s_time, $e_time, $cp_start, $cp_end); 
        $main_header = "
            <th style='width:90px;'>Vehicle No</th>
            <th>Group Name</th>
            <th>Distance Travelled (KM)</th>
            <th style='width:40px;'>Average Speed</th>
            <th>Time Taken [HH:MM]</th>            
            <th>Idle Time [HH:MM]</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Genset AC-Usage [HH:MM]</th>
            ";
        $main_data = '';
        
        
        if(empty($reports)){
            $main_data = "<td colspan='6' style='text-align:center'>No Data</td>";
        }
        else{
            $veh_mangr = new VehicleManager($customerno);
            foreach($reports as $thisvehicle){
                if(empty($thisvehicle)){
                   continue; 
                }
                
                foreach($thisvehicle as $report){
                    
                    $daily_data = GetExceptionDailyReport_Data($report->startdate, $report->vehicleid);
                    if($condition=='gt'){
                    if($report_type === 'distance' && $report->distance > $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'avg_speed' && $daily_data['avgspeed'] > $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'idle_time' && ($report->idletime/60) > $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'genset_avg' && $daily_data['genset'] > $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    }
                    
                    else{
                    if($report_type === 'distance' && $report->distance <= $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'avg_speed' && $daily_data['avgspeed'] <= $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'idle_time' && ($report->idletime/60) <= $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    elseif($report_type === 'genset_avg' && $daily_data['genset'] <= $report_type_input){
                        $main_data .= report_generation($report, $daily_data);
                    }
                    }
                }
            }
        } 
    }
}
?>
<div class="container">
<table class='table newTable' >
    <thead>
        <tr>
            <th colspan="100%" style='font-weight:bold;font-size:14px;'><?php echo $TableTitle; ?></th>
        </tr>
        <tr>
            <th colspan="100%">
                <div class="newTableSubHeader">
                    <div class="newTableSubHeaderLeft" style='width:75%'>
                        <?php echo $TableSubHeaderLeft; ?>
                    </div>
                </div>
                <div class="newTableSubHeader">
                    <div class="newTableSubHeaderRight" >
                        <?php echo $TableSubHeaderRight; ?>
                    </div>
                </div>
            </th>
        </tr>
    </thead>
</table>
</div>
<div class="clearfix"></div>

<div class="container">
<table class='table newTable' >
    <thead>
        <tr><?php echo $main_header; ?></tr>
    </thead>
    <tbody>
        <?php echo $main_data; ?>
    </tbody>
</table>
</div>
