DELIMITER $$
DROP TRIGGER IF EXISTS after_vehicle_insert$$
CREATE TRIGGER `after_vehicle_insert` AFTER INSERT ON `vehicle`
 FOR EACH ROW BEGIN
    BEGIN

        IF NEW.customerno = 219 THEN

            SET @serverTime = NOW();
            SET @istDateTime = CONVERT_TZ(@serverTime, 'SYSTEM', '+05:30');

            INSERT INTO socketDB.vehicle
            (
            vehicleid,
            vehicleno,
            extbatt,
            odometer,
            lastupdated,
            curspeed,
            driverid,
            customerno,
            uid,
            isdeleted,
            kind,
            userid,
            groupid,
            branchid,
            overspeed_limit,
            average,
            modelid,
            manufacturing_month,
            manufacturing_year,
            purchase_date,
            tax_date,
            permit_date,
            fitness_date,
            start_meter_reading,
            fueltype,
            is_insured,
            status_id,
            temp1_min,
            temp1_max,
            temp1_mute,
            temp2_min,
            temp2_max,
            temp2_mute,
            temp3_min,
            temp3_max,
            temp3_mute,
            temp4_min,
            temp4_max,
            temp4_mute,
            no_of_genset,
            genset1,
            genset2,
            transmitter1,
            transmitter2,
            puc_filename,
            registration_filename,
            insurance_filename,
            speed_gov_filename,
            fire_extinguisher_filename,
            other_upload5,
            other_upload6,
            other_upload1,
            other_upload2,
            other_upload3,
            other_upload4,
            `timestamp`,
            stoppage_odometer,
            stoppage_transit_time,
            nodata_alert,
            stoppage_flag,
            submission_date,
            registration_date,
            approval_date,
            additional_amount,
            description,
            sms_count,
            sms_lock,
            tel_count,
            tel_lock,
            fuel_balance,
            fuelcapacity,
            fuelMaxVoltCapacity,
            max_voltage,
            fuel_min_volt,
            fuel_max_volt,
            notes,
            rto_location,
            current_location,
            authorized_signatory,
            hypothecation,
            serial_number,
            expiry_date,
            owner_name,
            invcustid,
            sequenceno,
            hum_min,
            hum_max,
            checkpointId,
            chkpoint_status,
            checkpoint_timestamp,
            ignition_wirecut,
            isVehicleResetCmdSent,
            createdOn)
        VALUES
            (NEW.vehicleid
            ,NEW.vehicleno
            ,NEW.extbatt
            ,NEW.odometer
            ,NEW.lastupdated
            ,NEW.curspeed
            ,NEW.driverid
            ,NEW.customerno
            ,NEW.uid
            ,NEW.isdeleted
            ,NEW.kind
            ,NEW.userid
            ,NEW.groupid
            ,NEW.branchid
            ,NEW.overspeed_limit
            ,NEW.average
            ,NEW.modelid
            ,NEW.manufacturing_month
            ,NEW.manufacturing_year
            ,NEW.purchase_date
            ,NEW.tax_date
            ,NEW.permit_date
            ,NEW.fitness_date
            ,NEW.start_meter_reading
            ,NEW.fueltype
            ,NEW.is_insured
            ,NEW.status_id
            ,NEW.temp1_min
            ,NEW.temp1_max
            ,NEW.temp1_mute
            ,NEW.temp2_min
            ,NEW.temp2_max
            ,NEW.temp2_mute
            ,NEW.temp3_min
            ,NEW.temp3_max
            ,NEW.temp3_mute
            ,NEW.temp4_min
            ,NEW.temp4_max
            ,NEW.temp4_mute
            ,NEW.no_of_genset
            ,NEW.genset1
            ,NEW.genset2
            ,NEW.transmitter1
            ,NEW.transmitter2
            ,NEW.puc_filename
            ,NEW.registration_filename
            ,NEW.insurance_filename
            ,NEW.speed_gov_filename
            ,NEW.fire_extinguisher_filename
            ,COALESCE(NEW.other_upload5,'')
            ,COALESCE(NEW.other_upload6,'')
            ,COALESCE(NEW.other_upload1,'')
            ,COALESCE(NEW.other_upload2,'')
            ,COALESCE(NEW.other_upload3,'')
            ,COALESCE(NEW.other_upload4,'')
            ,COALESCE(NEW.`timestamp`,'0000-00-00 00:00:00')
            ,COALESCE(NEW.stoppage_odometer,'')
            ,COALESCE(NEW.stoppage_transit_time,'0000-00-00 00:00:00')
            ,NEW.nodata_alert
            ,NEW.stoppage_flag
            ,COALESCE(NEW.submission_date,'0000-00-00 00:00:00')
            ,COALESCE(NEW.registration_date,'0000-00-00 00:00:00')
            ,NEW.approval_date
            ,NEW.additional_amount
            ,NEW.description
            ,NEW.sms_count
            ,NEW.sms_lock
            ,NEW.tel_count
            ,NEW.tel_lock
            ,NEW.fuel_balance
            ,NEW.fuelcapacity
            ,NEW.fuelMaxVoltCapacity
            ,NEW.max_voltage
            ,NEW.fuel_min_volt
            ,NEW.fuel_max_volt
            ,NEW.notes
            ,NEW.rto_location
            ,NEW.current_location
            ,NEW.authorized_signatory
            ,NEW.hypothecation
            ,NEW.serial_number
            ,NEW.expiry_date
            ,NEW.owner_name
            ,NEW.invcustid
            ,NEW.sequenceno
            ,NEW.hum_min
            ,NEW.hum_max
            ,NEW.checkpointId
            ,NEW.chkpoint_status
            ,NEW.checkpoint_timestamp
            ,NEW.ignition_wirecut
            ,NEW.isVehicleResetCmdSent
            ,@istDateTime
            );
    END IF;
END;
END$$
DELIMITER ;