<div class="container">
<table class='table newTable' >
    <thead>
        <tr>
            <th colspan="100%" style='font-weight:bold;font-size:14px;'>Trip Report</th>
        </tr>
        <tr>
            <th colspan="100%">
                <div class="newTableSubHeader">
                    <div class="newTableSubHeaderLeft">
                    Vehicle No: <?php echo $_POST['vehicleno']; ?><br/>
                    Start Date: <?php echo $_POST['STdate'].' '.$_POST['STime']; ?><br/>
                    End Date: <?php echo $_POST['EDdate'].' '.$_POST['ETime']; ?><br/>
                    </div>
                </div>
                <div class="newTableSubHeader">
                    <div class="newTableSubHeaderRight">
                    Generated by: <?php echo $_SESSION['username']; ?><br/>
                    Generated on: <?php echo date('d-m-Y h:i'); ?>
                    </div>
                </div>
            </th>
        </tr>
    </thead>
</table>
</div>
<div class="clearfix"></div>

<div class="container">
<table class='table newTable' id='search_table_2'>
    <thead>
        <tr>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Starting location</th>            
            <th>End location</th>
            <th>Distance</th>
            <th>Map View</th>
            <th>Table View</th>
        </tr>
    </thead>
    <tbody>