<?php
include_once '../../lib/system/Validator.php';
include_once '../../lib/system/VersionedManager.php';
include_once '../../lib/system/Sanitise.php';
include_once '../../lib/system/Date.php';
include_once '../../lib/model/VOElixiaCode.php';

class ElixiaCodeManager extends VersionedManager
{

    function __construct($customerno) {
        // Constructor.
        parent::__construct($customerno);
    }

    public function SaveElixiaCode($elixiacode, $userid)
    {
        $Query = "INSERT INTO elixiacode (`customerno`,`startdate`,`expirydate`,`ecode`,`datecreated`,isdeleted, userid, ecodeemail, ecodesms, menuoption,days) VALUES ( '%d','%s','%s','%d','%s',0,%d,'%s','%s',%d,%d)";
        $SQL = sprintf($Query,$this->_Customerno, Sanitise::DateTime($elixiacode->startdate),Sanitise::DateTime($elixiacode->expirydate), Sanitise::Long($elixiacode->ecode),
                Sanitise::DateTime($elixiacode->datecreated), Sanitise::Long($userid), Sanitise::String($elixiacode->email),Sanitise::String($elixiacode->sms),Sanitise::Long($elixiacode->menu),Sanitise::Long($elixiacode->days));
        $this->_databaseManager->executeQuery($SQL);
        $elixiacode->id = $this->_databaseManager->get_insertedId();
        $Query = "INSERT INTO ecodeman (`customerno`,`vehicleid`,`ecodeid`,isdeleted, userid) VALUES ( '%d','%d','%d',0,%d)";
        foreach($elixiacode->vehicles as $vehicle)
        {
            $SQL = sprintf($Query, $this->_Customerno, Sanitise::Long($vehicle), Sanitise::Long($elixiacode->id), Sanitise::Long($userid));
            $this->_databaseManager->executeQuery($SQL);
        }

//        if($elixiacode->email != ''){
//        $today = date("Y-m-d H:i:s");
//        $subject = 'Elixia Code';
//        $message = 'Your Elixia Code is '.$elixiacode->ecode.'. <br/>Generated by '.$_SESSION['realname'].'. <br/>Please visit www.elixiatech.com/speed and trace your vehicle. <br/> Valid Until: '.convertDateToFormat($elixiacode->expirydate,speedConstants::DEFAULT_DATETIME);
//        $SQL = sprintf( "INSERT INTO communicationqueue
//                        (`type`,`email`,`subject`,`message`,`datecreated`,`customerno`) VALUES
//                        ( 0,'%s','%s','%s','%s','%d')",
//        Sanitise::String($elixiacode->email),
//        Sanitise::String($subject),
//        Sanitise::String($message),
//        Sanitise::DateTime($today),
//        Sanitise::Long($this->_Customerno));
//        $this->_databaseManager->executeQuery($SQL);
//        }
//
//        if($elixiacode->sms != ''){
//        $today = date("Y-m-d H:i:s");
//        $message = 'Elixia Code: '.$elixiacode->ecode.'. Generated by '.$_SESSION['realname'].'. Validity: '.convertDateToFormat($elixiacode->expirydate,speedConstants::DEFAULT_DATETIME).'. Link: www.elixiatech.com/speed';
//        $SQL = sprintf( "INSERT INTO communicationqueue
//                        (`type`,`phone`,`message`,`datecreated`,`customerno`) VALUES
//                        ( 1,'%s','%s','%s','%d')",
//        Sanitise::String($elixiacode->sms),
//        Sanitise::String($message),
//        Sanitise::DateTime($today),
//        Sanitise::Long($this->_Customerno));
//        $this->_databaseManager->executeQuery($SQL);
//        }
        return $elixiacode->id;
    }


    public function UpdateElixiaCode($elixiacode, $userid)
    {
        $Query = "UPDATE elixiacode SET startdate='%s', expirydate='%s', ecodeemail='%s', ecodesms='%s', menuoption=%d ,days=%d
                   WHERE customerno=%d AND ecode=%d AND isdeleted=0";
         $SQL = sprintf($Query, Sanitise::DateTime($elixiacode->startdate),Sanitise::DateTime($elixiacode->expirydate),  Sanitise::String($elixiacode->email),  Sanitise::string($elixiacode->sms),Sanitise::Long($elixiacode->menu),$elixiacode->days, $this->_Customerno, Sanitise::Long($elixiacode->ecode));
         $this->_databaseManager->executeQuery($SQL);
         $delQuery = sprintf("DELETE FROM ecodeman WHERE customerno=%d AND ecodeid=%d", $this->_Customerno,$elixiacode->eid);
         $this->_databaseManager->executeQuery($delQuery);
        $Query = "INSERT INTO ecodeman (`customerno`,`vehicleid`,`ecodeid`,isdeleted, userid) VALUES ( '%d','%d','%d',0,%d)";
        foreach ($elixiacode->vehicles as $vehicle)
        {
            $SQL = sprintf($Query, $this->_Customerno, Sanitise::Long($vehicle), Sanitise::Long($elixiacode->eid), Sanitise::Long($userid));
            $this->_databaseManager->executeQuery($SQL);
        }
        //return $elixiacode->id;
    }

    public function InsertEcodeHistory($elixiacode)
    {
        $Query = "INSERT INTO ecodehistory (`elixiacodeid`,`comdetail`,`type`,`userid`,`customerno`) VALUES ( '%d','%s','%d','%d',%d)";
        $SQL = sprintf($Query, Sanitise::Long($elixiacode->ecodeid), Sanitise::String($elixiacode->comdet),Sanitise::Long($elixiacode->type),Sanitise::Long($elixiacode->userid),$this->_Customerno);
        $this->_databaseManager->executeQuery($SQL);
    }

    public function getelixiacodesforcustomer()
    {
        $codes = Array();
        $Query = "SELECT * FROM `elixiacode` WHERE customerno=%d AND isdeleted=0";
        $elixiacodesQuery = sprintf($Query,$this->_Customerno);
        $this->_databaseManager->executeQuery($elixiacodesQuery);

        if ($this->_databaseManager->get_rowCount() > 0)
        {
            while ($row = $this->_databaseManager->get_nextRow())
            {
                $code = new VOElixiaCode();
                $code->id = $row['id'];
                $code->customerno = $row['customerno'];
                $code->datecreated = $row['datecreated'];
                $code->ecode = $row['ecode'];
                $code->startdate = $row['startdate'];
                $code->expirydate = $row['expirydate'];
                $checkstatus = $this->checkvalidity($row["expirydate"]);
                if($checkstatus == true)
                {
                    $code->status = "Valid";
                }
                else
                {
                    $code->status = "Expired";
                }
                $code->ecodeemail = $row['ecodeemail'];
                $code->ecodesms = $row['ecodesms'];
                $code->days = $row['days'];
                $codes[] = $code;
            }
            return $codes;
        }
        return null;
    }

    public function checkvalidity($expirydate)
    {
        $today = date('Y-m-d H:i:s');
        if(strtotime($today)<=strtotime($expirydate))
        {
            return TRUE;
        }
        else {
            return FALSE;
        }
    }

    public function DeleteElixiaCode($id, $userid)
    {
        $Query = "UPDATE elixiacode SET isdeleted=1, userid=%d WHERE id = %d and customerno = %d";
        $SQL = sprintf($Query,  Sanitise::Long($userid), Sanitise::Long($id), $this->_Customerno);
        $this->_databaseManager->executeQuery($SQL);
        $Query = "UPDATE ecodeman SET isdeleted=1, userid=%d WHERE ecodeid = %d and customerno = %d";
        $SQL = sprintf($Query, Sanitise::Long($userid), Sanitise::Long($id), $this->_Customerno);
        $this->_databaseManager->executeQuery($SQL);
        return true;
    }

    public function DeleteElixiaCodeByVehicle($id, $userid, $vehicleid)
    {
        $Query = "UPDATE ecodeman SET isdeleted=1, userid=%d WHERE ecodeid = %d and vehicleid=%d and customerno = %d";
        echo $SQL = sprintf($Query, Sanitise::Long($userid), Sanitise::Long($id), Sanitise::Long($vehicleid), $this->_Customerno);
        $this->_databaseManager->executeQuery($SQL);
    }

    public function getecodedvehicles()
    {
        $codes = Array();
        $Query = "SELECT ecodeman.ecodeid,ecodeman.vehicleid,vehicle.vehicleno
            FROM `ecodeman` INNER JOIN vehicle ON vehicle.vehicleid = ecodeman.vehicleid
            WHERE ecodeman.customerno=%d AND ecodeman.isdeleted=0 AND vehicle.isdeleted=0";
        $elixiacodesQuery = sprintf($Query, $this->_Customerno);
        $this->_databaseManager->executeQuery($elixiacodesQuery);

        if ($this->_databaseManager->get_rowCount() > 0)
        {
            while ($row = $this->_databaseManager->get_nextRow())
            {
                $code = new VOElixiaCode();
                $code->id = $row['ecodeid'];
                $code->vehicleid = $row['vehicleid'];
                $code->vehicleno = $row['vehicleno'];
                $codes[] = $code;
            }
            return $codes;
        }
        return null;
    }

    public function get_ecode_vehicles($vehicleid)
    {
        $codes = Array();

        $Query = "SELECT * FROM `elixiacode` INNER JOIN ecodeman on elixiacode.id = ecodeman.ecodeid
            WHERE ecodeman.customerno=%d AND ecodeman.isdeleted=0 AND vehicleid=%d";
        $elixiacodesQuery = sprintf($Query, $this->_Customerno, $vehicleid);
        $this->_databaseManager->executeQuery($elixiacodesQuery);

        if ($this->_databaseManager->get_rowCount() > 0)
        {
            while ($row = $this->_databaseManager->get_nextRow())
            {
                $code = new VOElixiaCode();
                $code->id = $row['id'];
                $code->vehicleid = $row['vehicleid'];
                $code->ecode = $row['ecode'];
                $code->datecreated = $row['datecreated'];
                $code->expirydate = $row['expirydate'];
                $codes[] = $code;
            }
            return $codes;
        }
        return null;
    }

    public function getElixiaCode($code)
    {

        $Query = "SELECT * FROM elixiacode WHERE customerno=%d AND id=%d ";
        $SQL = sprintf($Query,$this->_Customerno,  Sanitise::Long($code));
        $this->_databaseManager->executeQuery($SQL);
        if($this->_databaseManager->get_rowCount() > 0)
        {
           $row = $this->_databaseManager->get_nextRow();
           if($row)
           {
               $ecode = new VOElixiaCode();
               $ecode->id = $row['id'];
               $ecode->ecodeid = $row['ecode'];
               $ecode->startdate = $row['startdate'];
               $ecode->enddate = $row['expirydate'];
               $ecode->email = $row['ecodeemail'];
               $ecode->sms=$row['ecodesms'];
               $ecode->menu = $row['menuoption'];
               $ecode->days = $row['days'];
               return $ecode;
           }
           return null;
        }
        return null;
    }

    public function getCodeVehicle($code)
    {
        $vehicles = Array();
        $Query = "SELECT ecodeman.vehicleid, vehicle.vehicleno FROM ecodeman
                  INNER JOIN vehicle ON vehicle.vehicleid = ecodeman.vehicleid
                  INNER JOIN elixiacode ON elixiacode.id = ecodeman.ecodeid
                  WHERE ecodeman.customerno=%d AND ecodeman.ecodeid=%d AND ecodeman.isdeleted=0";
        $SQL = sprintf($Query, $this->_Customerno,  Sanitise::Long($code));
        $this->_databaseManager->executeQuery($SQL);
        if($this->_databaseManager->get_rowCount() > 0)
        {
            while($row = $this->_databaseManager->get_nextRow())
            {
                $vehicle = new VOVehicle();
                $vehicle->vehicleid = $row['vehicleid'];
                $vehicle->vehicleno = $row['vehicleno'];
                $vehicles[] = $vehicle;
            }
            return $vehicles;
        }
        return null;
    }
}
