<div style="width:auto; height:30px;">
    <table style="width: auto; border:none;">
        <tr>
            <td style="width:430px; border:none;"><img style="width:50%; height: 50%;" src="../../images/elixiaspeed_logo.png" /></td>
            <td style="width:420px; border:none;"><h3 style="text-transform:uppercase;"><?php echo $report_name; ?></h3><br /></td>
            <td style="width:230px;border:none;"><img src="../../images/elixia_logo_75.png"  /></td>
        </tr>
    </table>
</div><hr />
<style type="text/css">
table, td { border: solid 1px   }
hr.style-six { border: 0; height: 0; border-top: 1px solid rgba(0, 0, 0, 0.1); border-bottom: 1px solid rgba(255, 255, 255, 0.3); }
</style>
<table align="center" style="background-color:#CCCCCC;width: auto;font-weight:bold;font-size:13px; text-align:center;border-collapse:collapse; border:1px solid #000;">
<tbody>
    <tr><td colspan="2" style="width:600px;height:auto;"><?php echo $report_name; ?></td></tr>
    <tr>
        <td style="text-align:left;border-right:none;">
            Start Date:  <?php echo convertDateToFormat($STdate,speedConstants::DEFAULT_DATE); ?><br/>
            End Date: <?php echo convertDateToFormat($EDdate,speedConstants::DEFAULT_DATE);?> <br/>
            <?php 
            if (!is_null($vgroupname)) {?>
            Group-name: <?php echo $vgroupname; ?><br/>
        <?php } ?>
        </td>
        <td style="text-align:right;">
            Generated By: <?php echo $_SESSION['username'] ?><br/>
            Generated on: <?php echo date(speedConstants::DEFAULT_DATE); ?>
        </td>
    </tr>
</tbody>
</table><br/>

<table id='search_table_2' align='center' style='width: auto; font-size:13px; text-align:center;border-collapse:collapse; border:1px solid #000;'>
     <tbody>
        <tr  style='background-color:#CCCCCC;font-weight:bold;'>
            <td style='width:50px;height:auto;'>Vehicle No</td>
            <td style='width:900px;height:auto;'colspan='<?php echo count($totaldays);?>'> <?php echo $table_header; ?></td>
            <td style='width:50px;height:auto;'>Total</td>
        </tr>
        <?php echo $table_format; ?>
    </tbody>
</table>

<page_footer>[[page_cu]]/[[page_nb]]</page_footer>
<hr style='margin-top:5px;'>
<div align='right' style='text-align:center;'> Report Generated On: <?php echo date(speedConstants::DEFAULT_DATETIME); ?></div>
